version: '3.7'
services:
  mysql:
    build: ./db
    image: db:latest
    ports:
      target: 3306
      published: 3306
    volumes:
      type: volume
      source: db_users
      target: var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
  flask-app:
    build: ./flask-app
    image: rfarq75/flaskapp
    deploy:
      replicas: 4
    ports:
    - target: 5000
      published: 5000
      protocol: tcp 
    depends on:
    - "mysql"
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends on:
    - "flask-app"
volumes:
  db_users:
